Here are the docstrings for all methods in the class:

```
class ProphetVisualizer(BaseModelVisualizer):
    
    This class generates visualizations for Prophet models and performance metrics using PyStan.
    
    The class has three methods:
    
    1. generate_viz(self, data, model, model_version, forecast_period=7, forecast_frequency="D")
        
        Method to generate visualizations of Prophet model components and forecasts. 
    
        Args:
        
            data: pandas DataFrame
                Input DataFrame containing time-series data.
            model: Prophet model object
                A trained Prophet model object.
            model_version: str
                String defining the model version.
            forecast_period: int, default 7
                The period for which forecast is to be generated.
            forecast_frequency: str, default 'D'
                The frequency of the forecast period.
        
        Returns:
        
            None
        
        Description:
        
            This method generates two plots - component plot and forecast plot. The component plot shows the trends, seasonality, and holidays present in the dataset. The forecast plot visualizes the predicted values and uncertainty over the forecast period.
            

    
    2. cross_validation(self, model, model_version, initial, period, horizon)
        
        Method to perform time-series cross validation on the Prophet model.
    
        Args:
        
            model: Prophet model object
                A trained Prophet model object.
            model_version: str
                String defining the model version.
            initial: str, int or float
                String or numerical value to define the size of the initial training period.
            period: str, int or float
                String or numerical value to define the length of the spacing between cutoff dates.
            horizon: str, int or float
                String or numerical value to define the forecast horizon.
        
        Returns:
        
            None
        
        Description:
        
            This method performs time-series cross validation on the Prophet model. It generates performance metrics and plots for the cross-validation results. The plots show the actual versus predicted values and forecast errors over time. The performance metrics include mean absolute error, mean squared error, root mean squared error, and symmetry mean absolute percentage error. 
            

    
    3. _save_and_log_file(self, dir, id, file_name, model_version)
        
        Helper method to save plots generated by ProphetVisualizer methods to local directory and log them with the metadata tracker.
    
        Args:
        
            dir: str
                Directory path (String) for saving the file.
            id: str
                Unique identifier for the model version.
            file_name: str
                Name for the file to be saved.
            model_version: str
                String defining the model version.
        
        Returns:
        
            None
        
        Description:
        
            This method saves the plot generated by the calling function to a file and logs that file with the metadata tracker.  The file path is determined by appending the file_name to the directory path passed in as the dir argument. The name of the file is split to extract the file name and ignore the file extension. This name is used to log the file with the metadata tracker. 
```
