site_name: lolpop Documentation
docs_dir: src
site_description: A Software Engineering Framework for Machine Learning
site_url: https://lolpop.readthedocs.io
repo_url: https://github.com/jordanvolz/lolpop
edit_url: docs/src/
repo_name: lolpop
theme: 
  name: material
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.index
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tab.
plugins: 
  - search
markdown_extensions: 
  - toc: 
      permalink: true
      title: On this page 
  - abbr 
  - admonition
  - attr_list 
  - def_list 
  - footnotes 
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets 
  - pymdownx.tabbed: 
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra: 
  social: 
  - icon: fontawesome/brands/github
    link: https://github.com/jordanvolz/lolpop
  - icon: fontawesome/brands/discord
    link: https://discord.gg/4FmK7jERsh
nav: 
  - lolpop User Guide: 
    - Getting Started: 
      - Introduction: index.md
      - Installation: installation.md
      - Concepts: concepts.md 
      - Quickstart: quickstart.md
    - User Guide:
      - Overview: lolpop_overview.md
      - Configuration: configuration.md 
      - Building Workflows: building_workflows.md
      - Running Workflows: running_workflows.md
      - Testing Workflows: testing_workflows.md
      - lolpop Projects: lolpop_projects.md
    - Extensions: 
        - Overview: extensions.md
        - Creating an Extension: building_extensions.md
        - Using Extensions: using_extensions.md 
        - Packaging And Installing Extensions: packaging_extensions.md
        - Writing Tests: writing_extension_tests.md
        - Generating Documentation: writing_extension_documentation.md
        - Extending the CLI: extending_cli.md
    - CLI: 
      - Overview: cli.md
      - User Guide: cli_guide.md
      - Reference: cli_reference.md
    - Resources: 
      - About: about.md
      - Contributing: contributing.md
      - Community: community.md
      - Contact & Requesting Features: contact.md
  - Integrations: 
    - Overview: integrations.md
    - Components: 
      - Overview: components.md
      - BaseComponent: base_component.md
      - Data Checkers: 
        - BaseDataChecker: base_data_checker.md
        - Deepchecks: deepchecks_data_checker.md
        - EvidentlyAI: evidentlyai_data_checker.md
        - Stumpy: stumpy_matrix_profiler.md
      - Data Connectors: 
        - BaseDataConnector: base_data_connector.md
        - BigQuery: bigquery_data_connector.md
        - Databricks: databricks_sql_data_connector.md
        - DuckDB: duckdb_data_connector.md
        - Google Cloud Storage: gcs_data_connector.md
        - Local: local_data_connector.md
        - Postgres: postgres_data_connector.md
        - Redshift: redshift_data_connector.md
        - S3: s3_data_connector.md
        - Snowflake: snowflake_data_connector.md
      - Data Profilers:
        - BaseDataProfiler: base_data_profiler.md
        - EvidentlyAI: evidentlyai_data_profiler.md
        - Sweetviz: sweetviz_data_profiler.md
        - tslumen: tslumen_data_profiler.md
        - YData: ydata_data_profiler.md 
      - Data Splitter: 
        - BaseDataSplitter: base_data_splitter.md
        - Local: local_data_splitter.md
      - Data Synthesizers: 
        - BaseDataSynthesizer: base_data_synthesizer.md 
        - SDV: sdv_data_synthesizer.md
      - Data Transformers: 
        - BaseDataTransformer: base_data_transformer.md
        - Bigquery: bigquery_data_transformer.md
        - Databricks SQL: databricks_sql_data_transformer.md
        - dbt: dbt_data_transformer.md
        - DuckDB: duckdb_data_transformer.md
        - Local: local_data_transformer.md
        - Postgres: postgres_data_transformer.md
        - Redshift: redshift_data_transformer.md 
        - Snowflake: snowflake_data_transformer.md
      - Generative AI Chatbots: 
        - BaseGenAIChatbot: base_genai_chatbot.md
        - OpenAI: openai_chatbot.md 
      - Hyperparameter Tuners: 
        - BaseHyperparameterTuner: base_hyperparameter_tuner.md
        - Local: local_hyperparameter_tuner.md
        - Optuna: optuna_hyperparameter_tuner.md 
      - Loggers: 
        - BaseLogger: base_logger.md
        - File Logger: file_logger.md
        - StdOut Logger: stdout_logger.md
      - Metadata Trackers: 
        - BaseMetadataTracker: base_metadata_tracker.md
      - Metrics Trackers: 
        - BaseMetricsTracker: base_metrics_tracker.md
      - Model Bias Checker: 
        - BaseModelBiasChecker: base_model_bias_checker.md
        - AI Fairness 360: aifairness360_model_bias_checker.md
      - Model Checkers: 
        - BaseModelChecker: base_model_checker.md
      - Model Deployers: 
        - BaseModelDeployer: base_modeL_deployer.md
      - Model Explainers: 
        - BaseModelExplaieners: base_model_explainer.md
      - Model Repositories: 
        - BaseModelRespository: base_model_respository.md
      - Model Trainers: 
        - BaseModelTrainer: base_model_trainer.md
      - Model Visualizers: 
        - BaseModelVisualizer: base_model_visualizer.md
      - Notifiers: 
        - BaseNotifier: base_notifier.md
      - Resource Version Control: 
        - BaseResourceVersionControl: base_resource_version_control.md
    - Pipelines: 
      - Overview: pipelines.md
      - BasePipeline: basepipeline.md 
      - Deploy: 
        - BaseDeploy: base_deploy.md
        - Offline Deploy: offline_deploy.md
        - Metaflow Offline Deploy: metaflow_offlione_deploy.md 
      - Predict: 
        - BasePredict: base_predict.md
        - Offline Predict: offline_predict.md
        - Metaflow Offline Predict: metaflow_offline_predict.md
      - Process: 
        - BaseProcess: base_process.md
        - Offline Process: offline_process.md
        - Metaflow Offline Process: metaflow_offline_process.md
      - Train: 
        - BaseTrain: base_train.md
        - OfflineTrain: offline_train.md
        - Metaflow Offline Train: metaflow_offline_train.md 
      - Reconcile: 
        - BaseReconcile: base_reconcile.md
        - Offline Reconcile: offline_reconcile.md
        - Metaflow Offline Reconcile: metaflow_offline_reconcile.md
    - Runners: 
      - Overview: runners.md
      - Classification: 
        - Classification Runner: classification_runner.md
        - Metaflow Classification Runner: metaflow_classification_runner.md
      - Regression: 
        - Regression Runner: regression_runner.md
        - Metaflow Regression RunnerL: metaflow_regression_runner.md 
      - Time-Series: 
        - Time-Series Runner: timeseries_runner.md
        - Metaflow Time-Series Runner.md
  - Examples: 
    - Overview: examples.md
    - Classification: classification.md
    - Regression: regression.md 
    - Time Series Forecasting: timeseries_forecasting.md



